### ISSUE TITLE
Menu item sort order

### ISSUE THREAD

**Issue by znek** [erikdoe/ccmenu2#6]
The sort ordering of the menu item is aligned with the Pipeline view. I'd prefer to have the items sorted by status severity + last build date. Any plans to do this or do I really have to learn Swift (god forbid ;-)?

**Comment by erikdtw** [comment]
Sorting by last build time is planned for the next pre-release. It's in the roadmap as "remaining menu appearance options". Trying to get to feature parity with the old CCMenu before replacing it with CCMenu2 in the AppStore.

Sorting by status severity is not planned, but there will be a filter like in the old CCMenu, to hide pipelines that had a successful build and are not active. This is already implemented but was added after the last pre-release.

**Comment by erikdoe** [comment]
Sorting and filtering like in CCMenu 1 is now implemented.
